[package]
name = "tame-index"
version = "0.0.1"
edition = "2021"
rust-version = "1.70.0"
description = "Provides access to local and remote cargo registry indices"
license = "Apache-2.0 OR MIT"

[dependencies]
